###################
# Backend
###################
backend = "glx";
vsync = true;
use-damage = true;
glx-no-stencil = true;
glx-copy-from-front = false;
glx-no-rebind-pixmap = false;
xrender-sync-fence = true;
dbe = false;
unredir-if-possible = true;
daemon = true;
log-level = "warn";

###################
# Blur
###################
blur:
{
  method = "dual_kawase";
  size = 15;
  strength = 6;
};

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

###################
# Shadows
###################
# shadow = true;
# shadow-radius = 12;
# shadow-opacity = 0.45;
# shadow-offset-x = -7;
# shadow-offset-y = -5;
# shadow-color = "#c0caf5";
# crop-shadow-to-monitor = true;

###################
# Fading / animations
###################
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;

###################
# Opacity
###################
frame-opacity = 1;

###################
# Window detection
###################
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
detect-client-leader = true;
use-ewmh-active-win = true;

###################
# Rules - ONLY Kitty & Neovim get blur
###################
rules = (
  # Kitty - BLUR ENABLED
  {
    match = "class_g = 'kitty'";
    blur-background = true;
    opacity = 0.95;
    shadow = true;
  },
  {
    match = "class_g = 'Code'";
    blur-background = true;
    opacity = 0.95;
    shadow = true;
    
  },
  # Neovim - BLUR ENABLED
  {
    match = "class_g = 'neovim' || class_g = 'nvim' || class_g = 'Neovim'";
    blur-background = true;
    opacity = 0.95;
    shadow = true;
    animations = (
      {
        triggers = [ "open", "show" ];
        preset = "fly-in";
        direction = "right";
        duration = 0.4;
      },
      {
        triggers = [ "close", "hide" ];
        preset = "slide-out";
        direction = "down";
        duration = 0.4;
      }
    );
  },
    {
    match = "window_type = 'notification'";
    blur-background = false;
    corner-radius = 10;
    opacity = 0.9;
    shadow = true;
    animations = (
      {
        triggers = [ "open", "show" ];
        preset = "slide-in";
        direction = "down";
        duration = 0.35;
      },
      {
        triggers = [ "close", "hide" ];
        preset = "slide-out";
        direction = "up";
        duration = 0.35;
      }
    );
  },
  
);