
# ---- POLYBAR ----
exec_always --no-startup-id killall -q polybar
exec_always --no-startup-id ~/.config/polybar/launch_polybar.sh
exec_always --no-startup-id picom 

# ---- WALLPAPER ----
exec_always --no-startup-id feh --bg-scale ~/Rainnight.jpg

# ---- SYSTEM SERVERS ----
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec --no-startup-id nm-applet
exec --no-startup-id blueman-applet

# ---- CLIPBOARD ----
exec --no-startup-id copyq

# ---- FLAMESHOT ----
exec --no-startup-id flameshot

# ---- AUTOSTART DESKTOP FILES ----
exec --no-startup-id dex --autostart --environment i3

# ---- LOCK ON SUSPEND ----
exec --no-startup-id ~/.config/i3/scripts/start_xss_lock.sh


