wallpaper {
    monitor = eDP-1
    path = /home/satheem/Rainnight.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-1
    path = /home/satheem/Rainnight.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-2
    path = /home/satheem/Rainnight.jpg
    fit_mode = cover
}