wallpaper {
    monitor = eDP-1
    path = /home/satheem/a-wallpaper.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-1
    path = /home/satheem/a-wallpaper.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-2
    path = /home/satheem/a-wallpaper.jpg
    fit_mode = cover
}

# Disable quotesplash
splash = false
